import { useEffect, useState, type ReactNode } from "react";
import { Button } from "./button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "./dialog";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle } from "./alert-dialog";

export function NameDialog({open,title,description="请输入名称",initialValue="",submitLabel="确定",children,onCancel,onSubmit}:{open:boolean;title:string;description?:string;initialValue?:string;submitLabel?:string;children?:(name:string,setName:(value:string)=>void)=>ReactNode;onCancel:()=>void;onSubmit:(name:string)=>void}){
  const [name,setName]=useState(initialValue);useEffect(()=>{if(open)setName(initialValue)},[open,initialValue]);
  return <Dialog open={open} onOpenChange={value=>{if(!value)onCancel()}}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={event=>{event.preventDefault();const value=name.trim();if(value)onSubmit(value)}}><label className="grid gap-2 text-sm font-medium">名称<input autoFocus className="h-10 rounded-md border border-zinc-200 bg-white px-3 outline-none focus:ring-2 focus:ring-zinc-400" value={name} maxLength={200} onChange={event=>setName(event.target.value)}/></label>{children?.(name,setName)}<DialogFooter><Button type="button" variant="outline" onClick={onCancel}>取消</Button><Button type="submit" disabled={!name.trim()}>{submitLabel}</Button></DialogFooter></form></DialogContent></Dialog>
}

export function ConfirmDialog({open,title,description,confirmLabel="确认",destructive=false,onCancel,onConfirm}:{open:boolean;title:string;description:string;confirmLabel?:string;destructive?:boolean;onCancel:()=>void;onConfirm:()=>void}){return <AlertDialog open={open} onOpenChange={value=>{if(!value)onCancel()}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel asChild><Button variant="outline" onClick={onCancel}>取消</Button></AlertDialogCancel><AlertDialogAction asChild><Button variant={destructive?"destructive":"default"} onClick={onConfirm}>{confirmLabel}</Button></AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
