import { useRef, useState } from "react";
import { loadFromBlob, serializeAsJSON } from "@excalidraw/excalidraw";
import type { ExcalidrawImperativeAPI } from "@excalidraw/excalidraw/types/types";
import { ChevronLeft, ChevronRight, CircleHelp, Download, Library, Palette, Share2, SunMoon, Upload } from "lucide-react";

const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
export function EditorTools({api,name,onShare}:{api:ExcalidrawImperativeAPI|null;name:string;onShare:()=>void}){
  const [open,setOpen]=useState(true);const input=useRef<HTMLInputElement>(null);const [help,setHelp]=useState(false);
  const importScene=async(file?:File)=>{if(!api||!file)return;try{const data=await loadFromBlob(file,api.getAppState(),api.getSceneElements());api.updateScene({elements:data.elements,appState:data.appState,commitToHistory:true});if(data.files)api.addFiles(Object.values(data.files));api.setToast({message:"文件已导入"})}catch{api.setToast({message:"无法导入该文件"})}};
  const exportScene=()=>{if(!api)return;download(new Blob([serializeAsJSON(api.getSceneElementsIncludingDeleted(),api.getAppState(),api.getFiles(),"local")],{type:"application/json"}),`${name}.excalidraw`)};
  const theme=()=>{if(!api)return;api.updateScene({appState:{theme:api.getAppState().theme==="dark"?"light":"dark"}})};
  return <aside className={`editor-tools ${open?"open":"collapsed"}`}><button className="tools-collapse" onClick={()=>setOpen(!open)} title={open?"收起工具栏":"展开工具栏"}>{open?<ChevronRight size={16}/>:<ChevronLeft size={16}/>}</button>{open&&<><header><span>画布工具</span><small>常用操作</small></header><div className="tool-list"><button onClick={()=>input.current?.click()}><span><Upload size={15}/></span><div><b>导入</b><small>打开 .excalidraw 文件</small></div></button><input ref={input} hidden type="file" accept=".excalidraw,.json,application/json" onChange={e=>{void importScene(e.target.files?.[0]);e.target.value=""}}/><button onClick={exportScene}><span><Download size={15}/></span><div><b>导出</b><small>保存可编辑源文件</small></div></button><button onClick={theme}><span><SunMoon size={15}/></span><div><b>主题切换</b><small>浅色 / 深色</small></div></button><label className="tool-button"><span><Palette size={15}/></span><div><b>画布背景</b><small>选择背景颜色</small></div><input type="color" value={api?.getAppState().viewBackgroundColor||"#ffffff"} onChange={e=>api?.updateScene({appState:{viewBackgroundColor:e.target.value}})}/></label><button onClick={onShare}><span><Share2 size={15}/></span><div><b>分享</b><small>图片和协作链接</small></div></button><button onClick={()=>api?.toggleSidebar({name:"default",tab:"library",force:true})}><span><Library size={15}/></span><div><b>Library</b><small>打开素材库</small></div></button><button onClick={()=>setHelp(!help)}><span><CircleHelp size={15}/></span><div><b>帮助</b><small>快捷键与使用说明</small></div></button></div>{help&&<div className="tool-help"><b>常用快捷键</b><span>V · 选择</span><span>R · 矩形</span><span>A · 箭头</span><span>T · 文字</span><span>Ctrl/Cmd + Z · 撤销</span><a href="https://docs.excalidraw.com" target="_blank" rel="noreferrer">查看 Excalidraw 帮助 ↗</a></div>}</>}</aside>;
}
