import { useEffect, useState } from "react";
import { ChevronLeft, FolderTree, Menu, Plus } from "lucide-react";
import { api } from "../api";
import type { SpaceMode, TreeData, User } from "../types";
import { FileTree } from "./FileTree";
import { NameDialog } from "./ui/form-dialog";

const empty:TreeData={users:[],projects:[],folders:[],drawings:[]};
export function EditorFileSidebar({user,selectedId}:{user:User;selectedId:string}){const [open,setOpen]=useState(false);const [mode,setMode]=useState<SpaceMode>("user");const [tree,setTree]=useState(empty);const [projectDialog,setProjectDialog]=useState(false);const [error,setError]=useState("");const load=()=>api.tree().then(setTree).catch(()=>{});useEffect(()=>{if(open)void load()},[open]);const createProject=async(name:string)=>{setProjectDialog(false);try{await api.createProject(name);setMode("project");setError("");await load()}catch(reason){setError(reason instanceof Error?reason.message:"创建失败")}};return <><aside className={`editor-file-sidebar ${open?"open":"collapsed"}`}><button className="file-sidebar-toggle" onClick={()=>setOpen(!open)} title={open?"收起文件树":"展开文件树"}>{open?<ChevronLeft size={17}/>:<Menu size={17}/>}</button>{open&&<><header><b><FolderTree size={15}/>文件树</b><div><button className={mode==="user"?"active":""} onClick={()=>setMode("user")}>用户</button><button className={mode==="project"?"active":""} onClick={()=>setMode("project")}>项目</button></div></header>{error&&<p className="error notice tree-error">{error}</p>}{mode==="project"&&<button className="sidebar-new-project" onClick={()=>setProjectDialog(true)}><Plus size={14}/>新建项目</button>}<FileTree data={tree} mode={mode} currentUser={user} selectedId={selectedId} editable compact onMutated={load}/></>}</aside><NameDialog open={projectDialog} title="新建项目" description="项目空间中的所有成员都可以创建文件和目录。" onCancel={()=>setProjectDialog(false)} onSubmit={createProject}/></>}
