import { useMemo, useState } from "react";
import { ChevronDown, ChevronRight, FilePenLine, FilePlus2, Folder, FolderKanban, FolderOpen, FolderPlus, Pencil, Trash2, UserRound, Workflow } from "lucide-react";
import { api } from "../api";
import type { Drawing, DrawingType, Folder as FolderItem, SpaceMode, TreeData, User } from "../types";

type Props = {data:TreeData;mode:SpaceMode;currentUser:User;selectedId?:string;editable?:boolean;filter?:string;compact?:boolean;onMutated?:()=>void};
const dateTime=(value:number)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));

export function FileTree({data,mode,currentUser,selectedId,editable=false,filter="",compact=false,onMutated=()=>{}}:Props){
  const [expanded,setExpanded]=useState<Set<string>>(()=>new Set());
  const folders=useMemo(()=>data.folders.filter(f=>f.space===mode),[data,mode]);
  const drawings=useMemo(()=>data.drawings.filter(d=>d.space===mode&&(!filter||d.name.toLowerCase().includes(filter.toLowerCase()))),[data,mode,filter]);
  const toggle=(id:string)=>setExpanded(previous=>{const next=new Set(previous);next.has(id)?next.delete(id):next.add(id);return next});
  const ask=async(label:string,current="")=>{const value=prompt(label,current)?.trim();return value||null};
  const run=async(action:()=>Promise<unknown>)=>{try{await action();onMutated()}catch(error){alert(error instanceof Error?error.message:"操作失败")}};
  const createFile=async(target:{space:SpaceMode;folderId?:string|null;projectId?:string|null},type:DrawingType)=>{const name=await ask(type==="mermaid"?"新建 Mermaid 图名称":"新建画板名称",type==="mermaid"?"未命名 Mermaid":"未命名画板");if(name)await run(async()=>{const item=await api.create(name,{...target,type});window.location.href=`/d/${item.id}`})};
  const createFolder=async(input:{space:SpaceMode;userId?:string|null;projectId?:string|null;parentId?:string|null})=>{const name=await ask("新建目录名称");if(name)await run(()=>api.createFolder({name,...input}))};
  const actions=(children:React.ReactNode)=><span className="tree-actions">{children}</span>;
  const fileNode=(d:Drawing)=><div className={`tree-row file ${selectedId===d.id?"selected":""}`} key={d.id}>
    <a href={`/d/${d.id}`} title={`${d.name} · ${d.owner.username}`}><span className="node-icon">{d.type==="mermaid"?<Workflow size={16}/>:<FilePenLine size={16}/>}</span><span className="file-copy"><span className="node-label">{d.name}</span><span className="file-meta"><span>创建：{dateTime(d.createdAt)}</span><span>修改：{dateTime(d.updatedAt)}</span><span>创建人：{d.owner.username}</span><span>修改人：{d.updatedBy?.username||d.owner.username}</span></span></span></a>
    {editable&&actions(<><button title="重命名" onClick={async()=>{const name=await ask("修改文件名",d.name);if(name)await run(()=>api.rename(d.id,name))}}><Pencil size={14}/></button>{d.canDelete&&<button title="删除" className="danger" onClick={()=>confirm(`删除“${d.name}”？`)&&run(()=>api.remove(d.id))}><Trash2 size={14}/></button>}</>)}
  </div>;
  const createControls=(target:{space:SpaceMode;folderId?:string|null;projectId?:string|null},folderInput:{space:SpaceMode;userId?:string|null;projectId?:string|null;parentId?:string|null})=><><button title="新建子目录" onClick={()=>createFolder(folderInput)}><FolderPlus size={14}/></button><button title="新建 Excalidraw 画板" onClick={()=>createFile(target,"excalidraw")}><FilePlus2 size={14}/></button><button title="新建 Mermaid 图" onClick={()=>createFile(target,"mermaid")}><Workflow size={14}/></button></>;
  const folderNode=(folder:FolderItem):React.ReactNode=>{const open=expanded.has(folder.id)||Boolean(filter);const children=folders.filter(f=>f.parentId===folder.id);const files=drawings.filter(d=>d.folderId===folder.id);return <div className="tree-branch" key={folder.id}><div className="tree-row folder"><button className="tree-toggle" onClick={()=>toggle(folder.id)}>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><span className="node-icon">{open?<FolderOpen size={16}/>:<Folder size={16}/>}</span><span className="node-label" onDoubleClick={()=>toggle(folder.id)}>{folder.name}</span>{editable&&actions(<>{createControls({space:folder.space,folderId:folder.id,projectId:folder.projectId},{space:folder.space,userId:folder.userId,projectId:folder.projectId,parentId:folder.id})}{folder.canDelete&&<><button title="重命名" onClick={async()=>{const name=await ask("修改目录名",folder.name);if(name)await run(()=>api.renameFolder(folder.id,name))}}><Pencil size={14}/></button><button title="删除空目录" className="danger" onClick={()=>confirm(`删除空目录“${folder.name}”？`)&&run(()=>api.removeFolder(folder.id))}><Trash2 size={14}/></button></>}</>)}</div>{open&&<div className="tree-children">{children.map(folderNode)}{files.map(fileNode)}{!children.length&&!files.length&&<span className="tree-empty">空目录</span>}</div>}</div>};
  const root=(id:string,label:string,rootFolders:FolderItem[],rootFiles:Drawing[],controls:React.ReactNode)=>{const open=expanded.has(id)||Boolean(filter);return <div className="tree-branch" key={id}><div className="tree-row root"><button className="tree-toggle" onClick={()=>toggle(id)}>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><span className="node-icon">{mode==="user"?<UserRound size={16}/>:<FolderKanban size={16}/>}</span><span className="node-label">{label}</span>{editable&&actions(controls)}</div>{open&&<div className="tree-children">{rootFolders.map(folderNode)}{rootFiles.map(fileNode)}{!rootFolders.length&&!rootFiles.length&&<span className="tree-empty">暂无内容</span>}</div>}</div>};
  return <div className={`file-tree ${compact?"compact":""}`}>{mode==="user"?data.users.map(user=>root(`user:${user.id}`,user.username,folders.filter(f=>f.userId===user.id&&!f.parentId),drawings.filter(d=>d.owner.id===user.id&&!d.folderId),user.id===currentUser.id?createControls({space:"user"},{space:"user",userId:user.id}):null)):data.projects.map(project=>root(`project:${project.id}`,project.name,folders.filter(f=>f.projectId===project.id&&!f.parentId),drawings.filter(d=>d.projectId===project.id&&!d.folderId),<>{createControls({space:"project",projectId:project.id},{space:"project",projectId:project.id})}{project.canDelete&&<><button title="重命名项目" onClick={async()=>{const name=await ask("修改项目名",project.name);if(name)await run(()=>api.renameProject(project.id,name))}}><Pencil size={14}/></button><button title="删除空项目" className="danger" onClick={()=>confirm(`删除空项目“${project.name}”？`)&&run(()=>api.removeProject(project.id))}><Trash2 size={14}/></button></>}</>))}</div>;
}
