import { useMemo, useState } from "react";
import { ChevronDown, ChevronRight, FilePenLine, FilePlus2, Folder, FolderKanban, FolderOpen, FolderPlus, Pencil, Trash2, UserRound, Workflow } from "lucide-react";
import { api } from "../api";
import { MERMAID_TEMPLATES } from "../editor/mermaidTemplates";
import type { Drawing, DrawingType, Folder as FolderItem, SpaceMode, TreeData, User } from "../types";
import { ConfirmDialog,NameDialog } from "./ui/form-dialog";
import { expansionStorageKey,readTreeExpansion,toggleTreeExpansion } from "./treeExpansion";
import { buildTreeSearch } from "./treeSearch";

type Props = {data:TreeData;mode:SpaceMode;currentUser:User;selectedId?:string;editable?:boolean;filter?:string;compact?:boolean;onMutated?:()=>void};
type FileTarget={space:SpaceMode;folderId?:string|null;projectId?:string|null};
type FolderTarget={space:SpaceMode;userId?:string|null;projectId?:string|null;parentId?:string|null};
type NameAction={title:string;description?:string;initialValue?:string;submitLabel?:string;onSubmit:(name:string)=>Promise<unknown>};
type DeleteAction={title:string;description:string;onConfirm:()=>Promise<unknown>};
type CreateAction={target:FileTarget;type:DrawingType};
const dateTime=(value:number)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));

export function FileTree({data,mode,currentUser,selectedId,editable=false,filter="",compact=false,onMutated=()=>{}}:Props){
  const [expansion,setExpansion]=useState(()=>readTreeExpansion(currentUser.id));const [nameAction,setNameAction]=useState<NameAction|null>(null);const [deleteAction,setDeleteAction]=useState<DeleteAction|null>(null);const [createAction,setCreateAction]=useState<CreateAction|null>(null);const [templateId,setTemplateId]=useState(MERMAID_TEMPLATES[0].id);const [error,setError]=useState("");
  const expanded=useMemo(()=>new Set(expansion[mode]),[expansion,mode]);
  const search=useMemo(()=>buildTreeSearch(data,mode,filter),[data,mode,filter]);
  const folders=useMemo(()=>data.folders.filter(folder=>folder.space===mode&&search.folderIds.has(folder.id)),[data,mode,search]);
  const drawings=useMemo(()=>data.drawings.filter(drawing=>drawing.space===mode&&search.drawingIds.has(drawing.id)),[data,mode,search]);
  const toggle=(id:string)=>setExpansion(previous=>{const next=toggleTreeExpansion(previous,mode,id);localStorage.setItem(expansionStorageKey(currentUser.id),JSON.stringify(next));return next});
  const run=async(action:()=>Promise<unknown>)=>{try{await action();setError("");await onMutated()}catch(reason){setError(reason instanceof Error?reason.message:"操作失败")}};
  const askName=(action:NameAction)=>setNameAction(action);
  const confirmDelete=(action:DeleteAction)=>setDeleteAction(action);
  const createFile=(target:FileTarget,type:DrawingType)=>{setTemplateId(MERMAID_TEMPLATES[0].id);setCreateAction({target,type})};
  const submitCreate=async(name:string)=>{const action=createAction;if(!action)return;setCreateAction(null);const template=MERMAID_TEMPLATES.find(item=>item.id===templateId);try{const item=await api.create(name,{...action.target,type:action.type,mermaidCode:action.type==="mermaid"?template?.code:undefined});window.location.href=`/d/${item.id}`}catch(reason){setError(reason instanceof Error?reason.message:"创建失败")}};
  const createFolder=(input:FolderTarget)=>askName({title:"新建目录",description:"目录会创建在当前选择的位置。",onSubmit:name=>api.createFolder({name,...input})});
  const actions=(children:React.ReactNode)=><span className="tree-actions">{children}</span>;
  const fileNode=(d:Drawing)=><div className={`tree-row file ${selectedId===d.id?"selected":""}`} key={d.id}>
    <a href={`/d/${d.id}`} title={`${d.name} · ${d.owner.username}`}><span className="node-icon">{d.type==="mermaid"?<Workflow size={16}/>:<FilePenLine size={16}/>}</span><span className="file-copy"><span className="node-label">{d.name}</span><span className="file-meta"><span>创建：{dateTime(d.createdAt)}</span><span>修改：{dateTime(d.updatedAt)}</span><span>创建人：{d.owner.username}</span><span>修改人：{d.updatedBy?.username||d.owner.username}</span></span></span></a>
    {editable&&actions(<><button title="重命名" onClick={()=>askName({title:"修改文件名",initialValue:d.name,onSubmit:name=>api.rename(d.id,name)})}><Pencil size={14}/></button>{d.canDelete&&<button title="删除" className="danger" onClick={()=>confirmDelete({title:`删除“${d.name}”？`,description:"文件、画布内容和分享图片会一并删除，此操作无法撤销。",onConfirm:()=>api.remove(d.id)})}><Trash2 size={14}/></button>}</>)}
  </div>;
  const createControls=(target:FileTarget,folderInput:FolderTarget)=><><button title="新建子目录" onClick={()=>createFolder(folderInput)}><FolderPlus size={14}/></button><button title="新建 Excalidraw 画板" onClick={()=>createFile(target,"excalidraw")}><FilePlus2 size={14}/></button><button title="新建 Mermaid 图" onClick={()=>createFile(target,"mermaid")}><Workflow size={14}/></button></>;
  const folderNode=(folder:FolderItem):React.ReactNode=>{const open=expanded.has(folder.id)||Boolean(filter);const children=folders.filter(f=>f.parentId===folder.id);const files=drawings.filter(d=>d.folderId===folder.id);return <div className="tree-branch" key={folder.id}><div className="tree-row folder"><button className="tree-toggle" onClick={()=>toggle(folder.id)}>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><span className="node-icon">{open?<FolderOpen size={16}/>:<Folder size={16}/>}</span><span className="node-label" onDoubleClick={()=>toggle(folder.id)}>{folder.name}</span>{editable&&actions(<>{createControls({space:folder.space,folderId:folder.id,projectId:folder.projectId},{space:folder.space,userId:folder.userId,projectId:folder.projectId,parentId:folder.id})}{folder.canDelete&&<><button title="重命名" onClick={()=>askName({title:"修改目录名",initialValue:folder.name,onSubmit:name=>api.renameFolder(folder.id,name)})}><Pencil size={14}/></button><button title="删除空目录" className="danger" onClick={()=>confirmDelete({title:`删除目录“${folder.name}”？`,description:"只能删除不包含子目录或文件的空目录。",onConfirm:()=>api.removeFolder(folder.id)})}><Trash2 size={14}/></button></>}</>)}</div>{open&&<div className="tree-children">{children.map(folderNode)}{files.map(fileNode)}{!children.length&&!files.length&&<span className="tree-empty">空目录</span>}</div>}</div>};
  const root=(id:string,label:string,rootFolders:FolderItem[],rootFiles:Drawing[],controls:React.ReactNode)=>{const open=expanded.has(id)||Boolean(filter);return <div className="tree-branch" key={id}><div className="tree-row root"><button className="tree-toggle" onClick={()=>toggle(id)}>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><span className="node-icon">{mode==="user"?<UserRound size={16}/>:<FolderKanban size={16}/>}</span><span className="node-label">{label}</span>{editable&&actions(controls)}</div>{open&&<div className="tree-children">{rootFolders.map(folderNode)}{rootFiles.map(fileNode)}{!rootFolders.length&&!rootFiles.length&&<span className="tree-empty">暂无内容</span>}</div>}</div>};
  const visibleUsers=data.users.filter(user=>search.rootIds.has(user.id));const visibleProjects=data.projects.filter(project=>search.rootIds.has(project.id));
  return <><div className={`file-tree ${compact?"compact":""}`}>{error&&<p className="error notice tree-error">{error}</p>}{mode==="user"?visibleUsers.map(user=>root(`user:${user.id}`,user.username,folders.filter(f=>f.userId===user.id&&!f.parentId),drawings.filter(d=>d.owner.id===user.id&&!d.folderId),user.id===currentUser.id?createControls({space:"user"},{space:"user",userId:user.id}):null)):visibleProjects.map(project=>root(`project:${project.id}`,project.name,folders.filter(f=>f.projectId===project.id&&!f.parentId),drawings.filter(d=>d.projectId===project.id&&!d.folderId),<>{createControls({space:"project",projectId:project.id},{space:"project",projectId:project.id})}{project.canDelete&&<><button title="重命名项目" onClick={()=>askName({title:"修改项目名",initialValue:project.name,onSubmit:name=>api.renameProject(project.id,name)})}><Pencil size={14}/></button><button title="删除空项目" className="danger" onClick={()=>confirmDelete({title:`删除项目“${project.name}”？`,description:"只能删除不包含目录或文件的空项目。",onConfirm:()=>api.removeProject(project.id)})}><Trash2 size={14}/></button></>}</>))}{filter&&search.rootIds.size===0&&<p className="tree-search-empty">没有匹配的{mode==="user"?"用户、目录或文件":"项目、目录或文件"}</p>}</div>
    <NameDialog open={Boolean(nameAction)} title={nameAction?.title||"输入名称"} description={nameAction?.description} initialValue={nameAction?.initialValue} submitLabel={nameAction?.submitLabel} onCancel={()=>setNameAction(null)} onSubmit={name=>{const action=nameAction;setNameAction(null);if(action)void run(()=>action.onSubmit(name))}}/>
    <NameDialog open={Boolean(createAction)} title={createAction?.type==="mermaid"?"新建 Mermaid 图":"新建 Excalidraw 画板"} description={createAction?.type==="mermaid"?"输入名称并选择初始图表类型，创建后可在 Visimer 中继续编辑。":"输入新画板的名称。"} initialValue={createAction?.type==="mermaid"?"未命名 Mermaid":"未命名画板"} submitLabel="创建" onCancel={()=>setCreateAction(null)} onSubmit={submitCreate}>{createAction?.type==="mermaid"?()=> <label className="grid gap-2 text-sm font-medium">图表类型<select className="h-10 rounded-md border border-zinc-200 bg-white px-3 outline-none focus:ring-2 focus:ring-zinc-400" value={templateId} onChange={event=>setTemplateId(event.target.value)}>{MERMAID_TEMPLATES.map(template=><option value={template.id} key={template.id}>{template.name}</option>)}</select></label>:undefined}</NameDialog>
    <ConfirmDialog open={Boolean(deleteAction)} title={deleteAction?.title||"确认删除"} description={deleteAction?.description||"此操作无法撤销。"} confirmLabel="删除" destructive onCancel={()=>setDeleteAction(null)} onConfirm={()=>{const action=deleteAction;setDeleteAction(null);if(action)void run(action.onConfirm)}}/>
  </>;
}
